import type { PortraitTemplate } from "./portrait-types";

export const portraitTemplates: PortraitTemplate[] = [
  {
    id: "warm-professional",
    title: "暖调职场肖像",
    category: "professional",
    audience: "female",
    coverImage: "/templates/warm-professional.png",
    prompt: "高级商业职场写真，暖灰摄影棚，米色西装，腰部以上构图，柔和大窗主光，克制自然的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "自然闭嘴表情", "完整露出额头、耳朵和下颌"],
    tags: ["职场", "高级", "自然"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "korean-clean",
    title: "韩式清透写真",
    category: "korean",
    audience: "female",
    coverImage: "/templates/korean-clean.png",
    prompt: "韩式清透写真，明亮奶油色影棚，白色上衣，轻透自然妆容，胸像构图，柔和日光与轻微闭嘴微笑。",
    selfieRequirements: ["正面或轻微侧脸", "均匀自然光", "不要使用重度滤镜"],
    tags: ["韩式", "清透", "日光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "new-chinese",
    title: "新中式雅韵",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/new-chinese.png",
    prompt: "新中式高级写真，深红现代中式服装，深木色室内与纸屏风，优雅坐姿，电影感暖侧光，沉静自然表情。",
    selfieRequirements: ["清晰正脸自拍", "头发轮廓完整", "肩颈无遮挡"],
    tags: ["新中式", "电影感", "雅致"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "hong-kong-cinema",
    title: "港风电影肖像",
    category: "hong_kong",
    audience: "female",
    coverImage: "/templates/hong-kong-cinema.jpg",
    prompt: "九十年代港风电影写真，黑色缎面礼服，深绿色复古室内，腰部以上站姿，钨丝灯暖侧光，细腻胶片颗粒，克制自然的闭嘴表情。",
    selfieRequirements: ["正面或轻微侧脸", "五官清晰无遮挡", "自然闭嘴表情"],
    tags: ["港风", "胶片", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "french-soft",
    title: "法式柔光写真",
    category: "french",
    audience: "female",
    coverImage: "/templates/french-soft.jpg",
    prompt: "法式轻奢室内写真，象牙白丝质衬衫，奶油色公寓背景，优雅坐姿腰部以上构图，大窗柔光，低饱和奶油色调，自然闭嘴表情。",
    selfieRequirements: ["正面清晰自拍", "肩颈轮廓完整", "避免强烈顶光"],
    tags: ["法式", "柔光", "轻奢"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "golden-grassland",
    title: "落日草原写真",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/golden-grassland.jpg",
    prompt: "金色落日草原写真，飘逸奶油色长裙，远处低矮山丘，三分之二全身自然行走姿态，夕阳逆光勾勒发丝，温暖通透的高级旅拍质感。",
    selfieRequirements: ["清晰正脸自拍", "头发与脸部边缘完整", "表情自然放松"],
    tags: ["草原", "落日", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mono-art",
    title: "黑白艺术肖像",
    category: "art",
    audience: "unisex",
    coverImage: "/templates/mono-art.jpg",
    prompt: "博物馆级黑白艺术肖像，极简黑色高领服装，胸像三分之二侧脸构图，雕塑感伦勃朗光，丰富灰阶与真实皮肤纹理，沉静中性表情。",
    selfieRequirements: ["面部轮廓清晰", "正面或轻微侧脸", "不要佩戴遮脸饰品"],
    tags: ["黑白", "艺术", "光影"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "cherry-spring",
    title: "樱花春日写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/cherry-spring.jpg",
    prompt: "春日樱花园写真，淡粉色现代裙装，樱花枝环绕，腰部以上优雅回眸姿态，柔和阴天自然光，清新粉白色调，轻微闭嘴微笑。",
    selfieRequirements: ["正脸或轻微回眸角度", "均匀自然光", "头发轮廓完整"],
    tags: ["樱花", "春日", "清新"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-business",
    title: "男士商务精英",
    category: "mens",
    audience: "male",
    coverImage: "/templates/mens-business.jpg",
    prompt: "高级男士商务肖像，海军蓝西装与白衬衫，现代深灰摄影棚，腰部以上自然站姿，专业柔和主光，真实皮肤质感，自信友好的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "额头和下颌完整", "自然闭嘴表情"],
    tags: ["男士", "商务", "专业"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "urban-rain",
    title: "雨后都市街拍",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/urban-rain.jpg",
    prompt: "雨后都市时尚写真，驼色风衣，现代建筑街区与地面微弱反光，三分之二全身自然行走姿态，冷调柔和天光，高级时装杂志质感。",
    selfieRequirements: ["五官清晰无遮挡", "自然放松表情", "头肩轮廓完整"],
    tags: ["都市", "街拍", "时尚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "seaside-morning",
    title: "海边晨光旅拍",
    category: "travel",
    audience: "female",
    coverImage: "/templates/seaside-morning.jpg",
    prompt: "宁静海边晨光写真，浅蓝色飘逸长裙，浅色海面与干净沙滩，三分之二全身自然站姿，柔和清晨光线，通透蓝白色调与精致旅行杂志质感。",
    selfieRequirements: ["正面清晰自拍", "发际线与下颌完整", "轻松自然表情"],
    tags: ["海边", "晨光", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "autumn-ginkgo",
    title: "银杏秋日写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/autumn-ginkgo.jpg",
    prompt: "金色银杏秋日写真，肉桂色针织衫与长外套，安静公园背景，腰部以上放松姿态，午后暖光，真实季节色彩，温柔自然的闭嘴表情。",
    selfieRequirements: ["均匀光线自拍", "面部和头发清晰", "肩颈无遮挡"],
    tags: ["银杏", "秋日", "暖调"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-ink",
    title: "男士东方墨韵",
    category: "mens",
    audience: "male",
    coverImage: "/templates/mens-ink.jpg",
    prompt: "现代东方水墨感男士写真，深色立领外套，浅色肌理背景与克制水墨氛围，腰部以上三分之二侧身姿态，柔和定向光，沉稳中性表情。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "五官无遮挡", "自然中性表情"],
    tags: ["男士", "东方", "水墨"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "premium-studio",
    title: "海马体风高级肖像",
    category: "professional",
    audience: "female",
    coverImage: "/templates/premium-studio.jpg",
    prompt: "高端商业影棚肖像，灰棕色无缝摄影棚，剪裁利落的灰褐色正式西装，精致自然妆容，腰部以上端庄构图，大型柔光箱主光与轻微轮廓光，高级商业精修质感。",
    selfieRequirements: ["正面清晰自拍", "完整露出额头和下颌", "自然闭嘴表情"],
    tags: ["高级肖像", "西装", "影棚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "japanese-oxygen",
    title: "日系氧气少女",
    category: "japanese",
    audience: "female",
    coverImage: "/templates/japanese-oxygen.jpg",
    prompt: "日系氧气感生活写真，清爽白衬衫，明亮窗边公寓，腰部以上放松抓拍姿态，柔和自然日光，低饱和通透肤色，清新生活感与轻微闭嘴微笑。",
    selfieRequirements: ["自然光下清晰自拍", "正面或轻微侧脸", "避免重度滤镜"],
    tags: ["日系", "氧气感", "日光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "american-retro",
    title: "美式复古写真",
    category: "retro",
    audience: "female",
    coverImage: "/templates/american-retro.jpg",
    prompt: "美式复古胶片写真，经典牛仔外套，木质与皮革元素的复古室内，三分之二全身放松姿态，暖色钨丝灯光，真实模拟胶片颗粒，琥珀与青绿色调。",
    selfieRequirements: ["五官清晰无遮挡", "头肩轮廓完整", "自然自信表情"],
    tags: ["美式", "复古", "胶片"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "soft-bridal",
    title: "轻婚纱写真",
    category: "bridal",
    audience: "female",
    coverImage: "/templates/soft-bridal.jpg",
    prompt: "轻婚纱高级写真，简洁优雅的白色婚纱礼服与白色花艺影棚，三分之二全身构图，双手自然放置，象牙白色调与大面积柔光，高级婚礼杂志摄影质感。",
    selfieRequirements: ["正面清晰自拍", "头发轮廓完整", "肩颈无遮挡"],
    tags: ["婚纱", "花艺", "柔光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "black-gown",
    title: "黑色礼服写真",
    category: "bridal",
    audience: "female",
    coverImage: "/templates/black-gown.jpg",
    prompt: "高级晚宴黑色礼服写真，剪裁优雅的黑色正式礼服，深色奢华影棚，三分之二全身挺拔姿态，电影感聚光灯与克制金色高光，时尚杂志质感。",
    selfieRequirements: ["正面或轻微侧脸", "均匀清晰光线", "自然闭嘴表情"],
    tags: ["黑礼服", "晚宴", "聚光灯"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "classic-qipao",
    title: "经典旗袍写真",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/classic-qipao.jpg",
    prompt: "经典旗袍东方写真，深青色典雅旗袍，格栅窗与木质传统室内，腰部以上至三分之二全身优雅侧身姿态，温暖窗边侧光，沉静高级的东方肖像。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "肩颈轮廓完整", "沉静自然表情"],
    tags: ["旗袍", "东方", "木质"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "garden-hanfu",
    title: "园林汉服写真",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/garden-hanfu.jpg",
    prompt: "古典园林汉服写真，淡绿色典雅汉服与精致传统妆发，中式园林亭台背景，三分之二全身优雅站姿，柔和清晨自然光与轻微薄雾，含蓄清雅色调。",
    selfieRequirements: ["正面清晰自拍", "头发与脸部边缘完整", "自然中性表情"],
    tags: ["汉服", "园林", "古典"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "forest-backlight",
    title: "森系逆光写真",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/forest-backlight.jpg",
    prompt: "清新森系写真，浅奶油色飘逸长裙，茂密树林与草地，三分之二全身自然站姿，阳光穿过树叶形成柔和逆光与发丝轮廓，真实自然的植物系杂志质感。",
    selfieRequirements: ["头发轮廓完整", "正脸或轻微侧脸", "自然放松表情"],
    tags: ["森系", "树林", "逆光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "city-neon-night",
    title: "城市霓虹夜景",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/city-neon-night.jpg",
    prompt: "城市夜景电影写真，时尚深色外套，现代街道与雨后路面，腰部以上自然站姿，青色与洋红霓虹轮廓光，真实湿地反射与背景散景，高级电影剧照质感。",
    selfieRequirements: ["面部清晰无遮挡", "头肩轮廓完整", "自然自信表情"],
    tags: ["夜景", "霓虹", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "christmas-warm",
    title: "圣诞暖光写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/christmas-warm.jpg",
    prompt: "高级圣诞节日写真，深红色丝绒正式服装，精致圣诞树与暖色灯串室内，腰部以上自然坐姿，金色散景与柔和影棚光，温暖高级的节日贺卡摄影质感。",
    selfieRequirements: ["正面清晰自拍", "均匀自然光", "轻微闭嘴微笑"],
    tags: ["圣诞", "红色", "暖光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-white",
    title: "白底职业证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-white.jpg",
    prompt: "标准白底职业证件照，纯白无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面平视镜头", "完整露出额头、耳朵和下颌", "自然闭嘴且面部无遮挡"],
    tags: ["证件照", "白底", "职业"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-blue",
    title: "蓝底标准证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-blue.jpg",
    prompt: "标准蓝底证件照，纯净均匀的中蓝色无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面平视镜头", "头发与脸部边缘完整", "避免歪头、低头或侧脸"],
    tags: ["证件照", "蓝底", "标准"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-red",
    title: "红底正式证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-red.jpg",
    prompt: "标准红底正式证件照，纯净均匀的标准红色无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "肩颈端正且无遮挡", "自然中性闭嘴表情"],
    tags: ["证件照", "红底", "正式"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
];

export function getPortraitTemplate(id: string) {
  return portraitTemplates.find((template) => template.id === id);
}

