import type { PortraitTemplate } from "./portrait-types";

export const portraitTemplates: PortraitTemplate[] = [
  {
    id: "warm-professional",
    title: "暖调职场肖像",
    category: "professional",
    coverImage: "/templates/warm-professional.png",
    prompt: "高级商业职场写真，暖灰摄影棚，米色西装，腰部以上构图，柔和大窗主光，克制自然的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "自然闭嘴表情", "完整露出额头、耳朵和下颌"],
    tags: ["职场", "高级", "自然"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "korean-clean",
    title: "韩式清透写真",
    category: "korean",
    coverImage: "/templates/korean-clean.png",
    prompt: "韩式清透写真，明亮奶油色影棚，白色上衣，轻透自然妆容，胸像构图，柔和日光与轻微闭嘴微笑。",
    selfieRequirements: ["正面或轻微侧脸", "均匀自然光", "不要使用重度滤镜"],
    tags: ["韩式", "清透", "日光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "new-chinese",
    title: "新中式雅韵",
    category: "new_chinese",
    coverImage: "/templates/new-chinese.png",
    prompt: "新中式高级写真，深红现代中式服装，深木色室内与纸屏风，优雅坐姿，电影感暖侧光，沉静自然表情。",
    selfieRequirements: ["清晰正脸自拍", "头发轮廓完整", "肩颈无遮挡"],
    tags: ["新中式", "电影感", "雅致"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "hong-kong-cinema",
    title: "港风电影肖像",
    category: "hong_kong",
    coverImage: "/templates/hong-kong-cinema.jpg",
    prompt: "九十年代港风电影写真，黑色缎面礼服，深绿色复古室内，腰部以上站姿，钨丝灯暖侧光，细腻胶片颗粒，克制自然的闭嘴表情。",
    selfieRequirements: ["正面或轻微侧脸", "五官清晰无遮挡", "自然闭嘴表情"],
    tags: ["港风", "胶片", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "french-soft",
    title: "法式柔光写真",
    category: "french",
    coverImage: "/templates/french-soft.jpg",
    prompt: "法式轻奢室内写真，象牙白丝质衬衫，奶油色公寓背景，优雅坐姿腰部以上构图，大窗柔光，低饱和奶油色调，自然闭嘴表情。",
    selfieRequirements: ["正面清晰自拍", "肩颈轮廓完整", "避免强烈顶光"],
    tags: ["法式", "柔光", "轻奢"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "golden-grassland",
    title: "落日草原写真",
    category: "outdoor",
    coverImage: "/templates/golden-grassland.jpg",
    prompt: "金色落日草原写真，飘逸奶油色长裙，远处低矮山丘，三分之二全身自然行走姿态，夕阳逆光勾勒发丝，温暖通透的高级旅拍质感。",
    selfieRequirements: ["清晰正脸自拍", "头发与脸部边缘完整", "表情自然放松"],
    tags: ["草原", "落日", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mono-art",
    title: "黑白艺术肖像",
    category: "art",
    coverImage: "/templates/mono-art.jpg",
    prompt: "博物馆级黑白艺术肖像，极简黑色高领服装，胸像三分之二侧脸构图，雕塑感伦勃朗光，丰富灰阶与真实皮肤纹理，沉静中性表情。",
    selfieRequirements: ["面部轮廓清晰", "正面或轻微侧脸", "不要佩戴遮脸饰品"],
    tags: ["黑白", "艺术", "光影"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "cherry-spring",
    title: "樱花春日写真",
    category: "seasonal",
    coverImage: "/templates/cherry-spring.jpg",
    prompt: "春日樱花园写真，淡粉色现代裙装，樱花枝环绕，腰部以上优雅回眸姿态，柔和阴天自然光，清新粉白色调，轻微闭嘴微笑。",
    selfieRequirements: ["正脸或轻微回眸角度", "均匀自然光", "头发轮廓完整"],
    tags: ["樱花", "春日", "清新"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-business",
    title: "男士商务精英",
    category: "mens",
    coverImage: "/templates/mens-business.jpg",
    prompt: "高级男士商务肖像，海军蓝西装与白衬衫，现代深灰摄影棚，腰部以上自然站姿，专业柔和主光，真实皮肤质感，自信友好的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "额头和下颌完整", "自然闭嘴表情"],
    tags: ["男士", "商务", "专业"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "urban-rain",
    title: "雨后都市街拍",
    category: "outdoor",
    coverImage: "/templates/urban-rain.jpg",
    prompt: "雨后都市时尚写真，驼色风衣，现代建筑街区与地面微弱反光，三分之二全身自然行走姿态，冷调柔和天光，高级时装杂志质感。",
    selfieRequirements: ["五官清晰无遮挡", "自然放松表情", "头肩轮廓完整"],
    tags: ["都市", "街拍", "时尚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "seaside-morning",
    title: "海边晨光旅拍",
    category: "travel",
    coverImage: "/templates/seaside-morning.jpg",
    prompt: "宁静海边晨光写真，浅蓝色飘逸长裙，浅色海面与干净沙滩，三分之二全身自然站姿，柔和清晨光线，通透蓝白色调与精致旅行杂志质感。",
    selfieRequirements: ["正面清晰自拍", "发际线与下颌完整", "轻松自然表情"],
    tags: ["海边", "晨光", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "autumn-ginkgo",
    title: "银杏秋日写真",
    category: "seasonal",
    coverImage: "/templates/autumn-ginkgo.jpg",
    prompt: "金色银杏秋日写真，肉桂色针织衫与长外套，安静公园背景，腰部以上放松姿态，午后暖光，真实季节色彩，温柔自然的闭嘴表情。",
    selfieRequirements: ["均匀光线自拍", "面部和头发清晰", "肩颈无遮挡"],
    tags: ["银杏", "秋日", "暖调"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-ink",
    title: "男士东方墨韵",
    category: "mens",
    coverImage: "/templates/mens-ink.jpg",
    prompt: "现代东方水墨感男士写真，深色立领外套，浅色肌理背景与克制水墨氛围，腰部以上三分之二侧身姿态，柔和定向光，沉稳中性表情。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "五官无遮挡", "自然中性表情"],
    tags: ["男士", "东方", "水墨"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
];

export function getPortraitTemplate(id: string) {
  return portraitTemplates.find((template) => template.id === id);
}

