import type { PortraitTemplate } from "./portrait-types";

export const portraitTemplates: PortraitTemplate[] = [
  {
    id: "warm-professional",
    title: "暖调职场肖像",
    category: "professional",
    audience: "female",
    coverImage: "/templates/warm-professional.png",
    prompt: "高级商业职场写真，暖灰摄影棚，米色西装，腰部以上构图，柔和大窗主光，克制自然的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "自然闭嘴表情", "完整露出额头、耳朵和下颌"],
    tags: ["职场", "高级", "自然"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "korean-clean",
    title: "韩式清透写真",
    category: "korean",
    audience: "female",
    coverImage: "/templates/korean-clean.png",
    prompt: "韩式清透写真，明亮奶油色影棚，白色上衣，轻透自然妆容，胸像构图，柔和日光与轻微闭嘴微笑。",
    selfieRequirements: ["正面或轻微侧脸", "均匀自然光", "不要使用重度滤镜"],
    tags: ["韩式", "清透", "日光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "new-chinese",
    title: "新中式雅韵",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/new-chinese.png",
    prompt: "新中式高级写真，深红现代中式服装，深木色室内与纸屏风，优雅坐姿，电影感暖侧光，沉静自然表情。",
    selfieRequirements: ["清晰正脸自拍", "头发轮廓完整", "肩颈无遮挡"],
    tags: ["新中式", "电影感", "雅致"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "hong-kong-cinema",
    title: "港风电影肖像",
    category: "hong_kong",
    audience: "female",
    coverImage: "/templates/hong-kong-cinema.jpg",
    prompt: "九十年代港风电影写真，黑色缎面礼服，深绿色复古室内，腰部以上站姿，钨丝灯暖侧光，细腻胶片颗粒，克制自然的闭嘴表情。",
    selfieRequirements: ["正面或轻微侧脸", "五官清晰无遮挡", "自然闭嘴表情"],
    tags: ["港风", "胶片", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "french-soft",
    title: "法式柔光写真",
    category: "french",
    audience: "female",
    coverImage: "/templates/french-soft.jpg",
    prompt: "法式轻奢室内写真，象牙白丝质衬衫，奶油色公寓背景，优雅坐姿腰部以上构图，大窗柔光，低饱和奶油色调，自然闭嘴表情。",
    selfieRequirements: ["正面清晰自拍", "肩颈轮廓完整", "避免强烈顶光"],
    tags: ["法式", "柔光", "轻奢"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "golden-grassland",
    title: "落日草原写真",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/golden-grassland.jpg",
    prompt: "金色落日草原写真，飘逸奶油色长裙，远处低矮山丘，三分之二全身自然行走姿态，夕阳逆光勾勒发丝，温暖通透的高级旅拍质感。",
    selfieRequirements: ["清晰正脸自拍", "头发与脸部边缘完整", "表情自然放松"],
    tags: ["草原", "落日", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mono-art",
    title: "黑白艺术肖像",
    category: "art",
    audience: "unisex",
    coverImage: "/templates/mono-art.jpg",
    identityNeutralImage: "/templates/identity-neutral/mono-art.jpg",
    prompt: "博物馆级黑白艺术肖像，极简黑色高领服装，胸像三分之二侧脸构图，雕塑感伦勃朗光，丰富灰阶与真实皮肤纹理，沉静中性表情。",
    selfieRequirements: ["面部轮廓清晰", "正面或轻微侧脸", "不要佩戴遮脸饰品"],
    tags: ["黑白", "艺术", "光影"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "cherry-spring",
    title: "樱花春日写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/cherry-spring.jpg",
    prompt: "春日樱花园写真，淡粉色现代裙装，樱花枝环绕，腰部以上优雅回眸姿态，柔和阴天自然光，清新粉白色调，轻微闭嘴微笑。",
    selfieRequirements: ["正脸或轻微回眸角度", "均匀自然光", "头发轮廓完整"],
    tags: ["樱花", "春日", "清新"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-business",
    title: "男士商务精英",
    category: "mens",
    audience: "male",
    coverImage: "/templates/mens-business.jpg",
    identityNeutralImage: "/templates/identity-neutral/mens-business.jpg",
    prompt: "高级男士商务肖像，海军蓝西装与白衬衫，现代深灰摄影棚，腰部以上自然站姿，专业柔和主光，真实皮肤质感，自信友好的闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "额头和下颌完整", "自然闭嘴表情"],
    tags: ["男士", "商务", "专业"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "urban-rain",
    title: "雨后都市街拍",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/urban-rain.jpg",
    prompt: "雨后都市时尚写真，驼色风衣，现代建筑街区与地面微弱反光，三分之二全身自然行走姿态，冷调柔和天光，高级时装杂志质感。",
    selfieRequirements: ["五官清晰无遮挡", "自然放松表情", "头肩轮廓完整"],
    tags: ["都市", "街拍", "时尚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "seaside-morning",
    title: "海边晨光旅拍",
    category: "travel",
    audience: "female",
    coverImage: "/templates/seaside-morning.jpg",
    prompt: "宁静海边晨光写真，浅蓝色飘逸长裙，浅色海面与干净沙滩，三分之二全身自然站姿，柔和清晨光线，通透蓝白色调与精致旅行杂志质感。",
    selfieRequirements: ["正面清晰自拍", "发际线与下颌完整", "轻松自然表情"],
    tags: ["海边", "晨光", "旅拍"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "autumn-ginkgo",
    title: "银杏秋日写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/autumn-ginkgo.jpg",
    prompt: "金色银杏秋日写真，肉桂色针织衫与长外套，安静公园背景，腰部以上放松姿态，午后暖光，真实季节色彩，温柔自然的闭嘴表情。",
    selfieRequirements: ["均匀光线自拍", "面部和头发清晰", "肩颈无遮挡"],
    tags: ["银杏", "秋日", "暖调"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "mens-ink",
    title: "男士东方墨韵",
    category: "mens",
    audience: "male",
    coverImage: "/templates/mens-ink.jpg",
    identityNeutralImage: "/templates/identity-neutral/mens-ink.jpg",
    prompt: "现代东方水墨感男士写真，深色立领外套，浅色肌理背景与克制水墨氛围，腰部以上三分之二侧身姿态，柔和定向光，沉稳中性表情。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "五官无遮挡", "自然中性表情"],
    tags: ["男士", "东方", "水墨"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "premium-studio",
    title: "海马体风高级肖像",
    category: "professional",
    audience: "female",
    coverImage: "/templates/premium-studio.jpg",
    prompt: "高端商业影棚肖像，灰棕色无缝摄影棚，剪裁利落的灰褐色正式西装，精致自然妆容，腰部以上端庄构图，大型柔光箱主光与轻微轮廓光，高级商业精修质感。",
    selfieRequirements: ["正面清晰自拍", "完整露出额头和下颌", "自然闭嘴表情"],
    tags: ["高级肖像", "西装", "影棚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "japanese-oxygen",
    title: "日系氧气少女",
    category: "japanese",
    audience: "female",
    coverImage: "/templates/japanese-oxygen.jpg",
    prompt: "日系氧气感生活写真，清爽白衬衫，明亮窗边公寓，腰部以上放松抓拍姿态，柔和自然日光，低饱和通透肤色，清新生活感与轻微闭嘴微笑。",
    selfieRequirements: ["自然光下清晰自拍", "正面或轻微侧脸", "避免重度滤镜"],
    tags: ["日系", "氧气感", "日光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "american-retro",
    title: "美式复古写真",
    category: "retro",
    audience: "female",
    coverImage: "/templates/american-retro.jpg",
    prompt: "美式复古胶片写真，经典牛仔外套，木质与皮革元素的复古室内，三分之二全身放松姿态，暖色钨丝灯光，真实模拟胶片颗粒，琥珀与青绿色调。",
    selfieRequirements: ["五官清晰无遮挡", "头肩轮廓完整", "自然自信表情"],
    tags: ["美式", "复古", "胶片"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "soft-bridal",
    title: "轻婚纱写真",
    category: "bridal",
    audience: "female",
    coverImage: "/templates/soft-bridal.jpg",
    prompt: "轻婚纱高级写真，简洁优雅的白色婚纱礼服与白色花艺影棚，三分之二全身构图，双手自然放置，象牙白色调与大面积柔光，高级婚礼杂志摄影质感。",
    selfieRequirements: ["正面清晰自拍", "头发轮廓完整", "肩颈无遮挡"],
    tags: ["婚纱", "花艺", "柔光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "black-gown",
    title: "黑色礼服写真",
    category: "bridal",
    audience: "female",
    coverImage: "/templates/black-gown.jpg",
    prompt: "高级晚宴黑色礼服写真，剪裁优雅的黑色正式礼服，深色奢华影棚，三分之二全身挺拔姿态，电影感聚光灯与克制金色高光，时尚杂志质感。",
    selfieRequirements: ["正面或轻微侧脸", "均匀清晰光线", "自然闭嘴表情"],
    tags: ["黑礼服", "晚宴", "聚光灯"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "classic-qipao",
    title: "经典旗袍写真",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/classic-qipao.jpg",
    prompt: "经典旗袍东方写真，深青色典雅旗袍，格栅窗与木质传统室内，腰部以上至三分之二全身优雅侧身姿态，温暖窗边侧光，沉静高级的东方肖像。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "肩颈轮廓完整", "沉静自然表情"],
    tags: ["旗袍", "东方", "木质"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "garden-hanfu",
    title: "园林汉服写真",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/garden-hanfu.jpg",
    prompt: "古典园林汉服写真，淡绿色典雅汉服与精致传统妆发，中式园林亭台背景，三分之二全身优雅站姿，柔和清晨自然光与轻微薄雾，含蓄清雅色调。",
    selfieRequirements: ["正面清晰自拍", "头发与脸部边缘完整", "自然中性表情"],
    tags: ["汉服", "园林", "古典"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "forest-backlight",
    title: "森系逆光写真",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/forest-backlight.jpg",
    prompt: "清新森系写真，浅奶油色飘逸长裙，茂密树林与草地，三分之二全身自然站姿，阳光穿过树叶形成柔和逆光与发丝轮廓，真实自然的植物系杂志质感。",
    selfieRequirements: ["头发轮廓完整", "正脸或轻微侧脸", "自然放松表情"],
    tags: ["森系", "树林", "逆光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "city-neon-night",
    title: "城市霓虹夜景",
    category: "outdoor",
    audience: "female",
    coverImage: "/templates/city-neon-night.jpg",
    prompt: "城市夜景电影写真，时尚深色外套，现代街道与雨后路面，腰部以上自然站姿，青色与洋红霓虹轮廓光，真实湿地反射与背景散景，高级电影剧照质感。",
    selfieRequirements: ["面部清晰无遮挡", "头肩轮廓完整", "自然自信表情"],
    tags: ["夜景", "霓虹", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "christmas-warm",
    title: "圣诞暖光写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/christmas-warm.jpg",
    prompt: "高级圣诞节日写真，深红色丝绒正式服装，精致圣诞树与暖色灯串室内，腰部以上自然坐姿，金色散景与柔和影棚光，温暖高级的节日贺卡摄影质感。",
    selfieRequirements: ["正面清晰自拍", "均匀自然光", "轻微闭嘴微笑"],
    tags: ["圣诞", "红色", "暖光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "spring-flower-field",
    title: "春日花海写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/spring-flower-field.jpg",
    prompt: "春日花海旅行写真，浅粉色飘逸长裙，大片柔和粉彩花田，三分之二全身自然站姿，明亮柔和的清晨日光，通透空气感与高级旅行杂志质感。",
    selfieRequirements: ["正面或轻微侧脸", "头发轮廓完整", "自然闭嘴微笑"],
    tags: ["春日", "花海", "清新"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "summer-island",
    title: "夏日海岛写真",
    category: "travel",
    audience: "female",
    coverImage: "/templates/summer-island.jpg",
    prompt: "夏日海岛度假写真，优雅得体的白色度假长裙，碧蓝海水与干净天空，三分之二全身沿海岸自然行走姿态，明亮清新的夏日日光，高级度假广告质感。",
    selfieRequirements: ["五官清晰无遮挡", "发际线与下颌完整", "自然放松表情"],
    tags: ["海岛", "夏日", "度假"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "autumn-maple",
    title: "秋日红叶写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/autumn-maple.jpg",
    prompt: "秋日红叶旅行写真，驼色羊毛大衣，鲜艳红色枫叶林间小路，腰部以上至三分之二全身自然姿态，午后暖阳穿过红叶，浓郁季节色彩与电影旅行质感。",
    selfieRequirements: ["清晰正脸自拍", "头肩轮廓完整", "轻微闭嘴微笑"],
    tags: ["秋日", "红叶", "暖调"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "winter-snow",
    title: "冬日雪景写真",
    category: "seasonal",
    audience: "female",
    coverImage: "/templates/winter-snow.jpg",
    prompt: "冬日雪景写真，象牙白冬季大衣与围巾，安静覆雪树林与自然飘落的雪花，腰部以上自然站姿，柔和阴天光，纯净白色与冷蓝色调。",
    selfieRequirements: ["面部清晰无遮挡", "头发边缘完整", "自然中性表情"],
    tags: ["冬日", "雪景", "纯净"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "snow-mountain",
    title: "雪山旅拍",
    category: "travel",
    audience: "female",
    coverImage: "/templates/snow-mountain.jpg",
    prompt: "高山雪景旅行写真，精致奶油色户外大衣，壮阔雪山与安全观景台，三分之二全身自信站姿，清澈金色晨光与通透空气，高级户外时尚杂志质感。",
    selfieRequirements: ["正面清晰自拍", "头发与脸部边缘完整", "自然自信表情"],
    tags: ["雪山", "旅拍", "壮阔"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "desert-sunset",
    title: "沙漠落日写真",
    category: "travel",
    audience: "female",
    coverImage: "/templates/desert-sunset.jpg",
    prompt: "沙漠落日高级写真，得体飘逸的赤陶色长裙，广阔起伏沙丘，三分之二全身优雅站姿，戏剧性金色逆光与温暖电影阴影，高级沙漠时尚大片质感。",
    selfieRequirements: ["头发轮廓完整", "五官清晰无遮挡", "沉静自然表情"],
    tags: ["沙漠", "落日", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "jiangnan-water-town",
    title: "江南水乡写真",
    category: "travel",
    audience: "female",
    coverImage: "/templates/jiangnan-water-town.jpg",
    prompt: "江南水乡旅行写真，淡蓝色现代中式裙装，白墙黛瓦、石桥与安静河道，腰部以上至三分之二全身优雅行走姿态，薄雾清晨柔光，淡雅水墨色调。",
    selfieRequirements: ["正脸或轻微侧脸", "肩颈无遮挡", "沉静闭嘴表情"],
    tags: ["江南", "水乡", "水墨"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "paris-street",
    title: "巴黎街头写真",
    category: "travel",
    audience: "female",
    coverImage: "/templates/paris-street.jpg",
    prompt: "巴黎街头时尚写真，剪裁利落的米色风衣与简洁黑裙，石材建筑林立的优雅林荫大道与咖啡馆氛围，三分之二全身自信行走姿态，柔和阴天光与克制胶片色调。",
    selfieRequirements: ["面部清晰无遮挡", "头肩轮廓完整", "自然自信表情"],
    tags: ["巴黎", "街拍", "时尚"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "european-castle",
    title: "欧洲古堡写真",
    category: "travel",
    audience: "female",
    coverImage: "/templates/european-castle.jpg",
    prompt: "欧洲古堡高级旅行写真，优雅得体的深酒红色正式礼服，宏伟历史古堡庭院与石拱门，三分之二全身端庄站姿，柔和金色傍晚光线与电影历史氛围。",
    selfieRequirements: ["正面或轻微侧脸", "均匀清晰光线", "端庄自然表情"],
    tags: ["古堡", "欧洲", "礼服"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "punk-rock",
    title: "朋克摇滚写真",
    category: "art",
    audience: "female",
    coverImage: "/templates/punk-rock.jpg",
    prompt: "超写实朋克摇滚真人写真，黑色皮夹克与克制金属细节，真实地下摇滚场地后台，三分之二全身自信站姿，硬侧闪光混合暖色现场灯，粗粝但高级的音乐杂志质感。",
    selfieRequirements: ["五官清晰无遮挡", "头发轮廓完整", "自然自信表情"],
    tags: ["朋克", "摇滚", "硬光"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "cyber-neon",
    title: "赛博霓虹写真",
    category: "art",
    audience: "female",
    coverImage: "/templates/cyber-neon.jpg",
    prompt: "超写实赛博霓虹真人写真，结构感深色未来夹克，真实现代城市夜巷，腰部以上电影构图，青色与洋红霓虹在皮肤和布料上形成符合物理规律的反射，雨夜科幻电影剧照质感。",
    selfieRequirements: ["面部清晰无遮挡", "头肩轮廓完整", "自然中性表情"],
    tags: ["赛博", "霓虹", "科幻"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "y2k-millennium",
    title: "Y2K 千禧美学",
    category: "retro",
    audience: "female",
    coverImage: "/templates/y2k-millennium.jpg",
    prompt: "超写实 Y2K 千禧时尚真人写真，长袖银色夹克、白色高领上衣与宽松牛仔裤，带镀铬元素的千禧摄影棚，三分之二全身直立时尚姿态，直接机顶闪光与柔和补光。",
    selfieRequirements: ["正面清晰自拍", "完整头发轮廓", "自然闭嘴表情"],
    tags: ["Y2K", "千禧", "闪光灯"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "dark-gothic",
    title: "暗黑哥特写真",
    category: "art",
    audience: "female",
    coverImage: "/templates/dark-gothic.jpg",
    prompt: "超写实暗黑哥特真人写真，高领黑色丝绒礼服，深色历史石材室内与克制烛光，三分之二全身端庄构图，电影级低调窗光，丰富黑色材质层次与高级哥特时装质感。",
    selfieRequirements: ["正面或轻微侧脸", "均匀清晰自拍", "沉静自然表情"],
    tags: ["哥特", "暗黑", "丝绒"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "court-oil-photo",
    title: "油画宫廷肖像",
    category: "art",
    audience: "female",
    coverImage: "/templates/court-oil-photo.jpg",
    prompt: "超写实真人摄影的宫廷油画构图，华丽深酒红历史风宫廷礼服与欧洲古典沙龙，三分之二全身正式姿态，真实伦勃朗光线和古典油画配色，但必须保持明确的相机摄影质感与真实皮肤纹理。",
    selfieRequirements: ["五官清晰无遮挡", "头发与脸部边缘完整", "端庄中性表情"],
    tags: ["宫廷", "油画构图", "古典"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "magazine-editorial",
    title: "时尚杂志封面",
    category: "art",
    audience: "female",
    coverImage: "/templates/magazine-editorial.jpg",
    prompt: "超写实高端时尚杂志封面风真人肖像，利落象牙白西装与极简高级摄影棚，腰部以上具有掌控力的编辑肖像，精准美人碟主光与柔和补光，保留干净留白但不生成任何文字。",
    selfieRequirements: ["正面清晰自拍", "完整露出额头和下颌", "自然自信表情"],
    tags: ["杂志", "时尚", "高级"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "luxury-campaign",
    title: "奢侈品广告写真",
    category: "art",
    audience: "female",
    coverImage: "/templates/luxury-campaign.jpg",
    prompt: "超写实无品牌奢华广告真人写真，精致驼色羊绒大衣与低调首饰，抛光洞石建筑室内，三分之二全身优雅广告姿态，金色定向光与真实材质细节，高级奢华广告质感但不出现品牌。",
    selfieRequirements: ["面部清晰无遮挡", "肩颈轮廓完整", "克制自然表情"],
    tags: ["奢华", "广告", "羊绒"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "cinematic-still",
    title: "电影剧照写真",
    category: "art",
    audience: "female",
    coverImage: "/templates/cinematic-still.jpg",
    prompt: "超写实叙事电影剧照真人写真，深色剪裁外套与深夜安静车站，腰部以上偏心电影构图，现场钨丝灯混合冷色环境光，真实 35mm 电影颗粒和克制的故事情绪。",
    selfieRequirements: ["正脸或轻微侧脸", "头肩轮廓完整", "自然克制表情"],
    tags: ["电影", "剧照", "叙事"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "republic-era",
    title: "民国复古写真",
    category: "retro",
    audience: "female",
    coverImage: "/templates/republic-era.jpg",
    prompt: "超写实民国年代复古真人写真，历史风高领中式裙装与得体外套，老上海风格典雅室内，腰部以上至三分之二全身优雅姿态，暖色窗光与真实复古胶片色彩，高级年代剧摄影质感。",
    selfieRequirements: ["清晰正脸或轻微侧脸", "发际线完整", "沉静闭嘴表情"],
    tags: ["民国", "复古", "年代感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "wuxia-jianghu",
    title: "武侠江湖写真",
    category: "new_chinese",
    audience: "female",
    coverImage: "/templates/wuxia-jianghu.jpg",
    prompt: "超写实真人武侠电影写真，层叠深青色历史风侠客服装，云雾山路与竹林，三分之二全身沉稳侠客姿态，自然阴天山间光线，风吹动真实发丝和布料，高级实拍武侠电影剧照质感。",
    selfieRequirements: ["五官清晰无遮挡", "头发轮廓完整", "坚定自然表情"],
    tags: ["武侠", "江湖", "电影感"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-white",
    title: "白底职业证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-white.jpg",
    prompt: "标准白底职业证件照，纯白无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面平视镜头", "完整露出额头、耳朵和下颌", "自然闭嘴且面部无遮挡"],
    tags: ["证件照", "白底", "职业"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-blue",
    title: "蓝底标准证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-blue.jpg",
    prompt: "标准蓝底证件照，纯净均匀的中蓝色无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面平视镜头", "头发与脸部边缘完整", "避免歪头、低头或侧脸"],
    tags: ["证件照", "蓝底", "标准"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
  {
    id: "id-photo-red",
    title: "红底正式证件照",
    category: "id_photo",
    audience: "unisex",
    coverImage: "/templates/id-photo-red.jpg",
    prompt: "标准红底正式证件照，纯净均匀的标准红色无纹理背景，深色西装与白色衬衫，正面平视镜头，头肩居中、双肩水平、头部完整，均匀无阴影影棚光，端正自然闭嘴表情。",
    selfieRequirements: ["正面清晰单人自拍", "肩颈端正且无遮挡", "自然中性闭嘴表情"],
    tags: ["证件照", "红底", "正式"], aspectRatio: "3:4",
    rights: { source: "ai-original", commercialUse: true, modelReleaseRequired: false },
  },
];

export function getPortraitTemplate(id: string) {
  return portraitTemplates.find((template) => template.id === id);
}

